[tool.poetry]
name = "banded_matrices"
version = "0.2.0"
description = "Native (C++) implementation of Banded Matrices for TensorFlow"
readme = "README.md"
repository = "https://github.com/secondmind-labs/banded_matrices"
license = "Apache-2.0"
keywords = ["banded matrices", "linear algebra"]
authors = ["Banded matrices contributors <labs@secondmind.ai>"]
packages = [{include = "banded_matrices"}]
classifiers=[
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Operating System :: OS Independent",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
include = [
        "LICENCE",
        "dummy.c",
        "build.py",
        "build_backend.py",
        { path = "banded_matrices/lib/libbanded_matrices.*", format = "wheel" },
]
build = "build.py"

[tool.poetry.dependencies]
cmake = ">=3.26,<4.0"
numpy = ">=1.26,<2.0"
python = ">=3.10,<3.13"
tensorflow = ">=2.16,<2.22"

[tool.poetry.group.dev.dependencies]
cpplint = "^1.6.1"
mock = "^5.2.0"
black = "^25.1.0"
mypy = "^1.15.0"
pylint = "^3.3.0"
pytest = "^8.3.0"
pytest-benchmark = "^5.1.0"
pytest-black = "^0.6.0"
pytest-cov = "^6.0.0"
pytest-isort = "^4.0.0"
pytest-mock = "^3.14.0"
pytest-mypy = "^1.0.1"
pytest-pylint = "^0.21.0"
scipy = ">=1.11,<2.0"
taskipy = "^1.14.0"


[tool.pytest.ini_options]
addopts = "--ignore=banded_matrices/banded.py"
filterwarnings = [
    "ignore:`np.bool8` is a deprecated alias for `np.bool_`.*:DeprecationWarning"
]



[tool.taskipy.tasks]
lint = "pytest --pylint --cache-clear -m pylint -v && pytest --pylint --cache-clear -m pylint --pylint-rcfile=extrapylint"
mypy = "pytest --mypy --cache-clear -m mypy -v"
quicktest = "pytest -x --ff -rN -Wignore"
cpplint = "cpplint --output=junit --root=banded_matrices/cc banded_matrices/cc/src/banded_matrices/*.cc banded_matrices/cc/include/banded_matrices/*.hpp"
test = "pytest --pylint --mypy --black --isort --cache-clear -ra -v --cov banded_matrices --cov-report term --cov-report html:cover_html --junitxml=reports/junit.xml -o junit_family=xunit2 && pytest --pylint --cache-clear -m pylint --pylint-rcfile=extrapylint"
black = "black ."
isort = "isort --atomic -y"
format = "task isort && task black"
check_format = "pytest -v --cache-clear --black --isort -m 'black or isort'"

[tool.black]
line-length = 95
target-version = ['py310']

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
line_length = 95



[build-system]
requires = [
    "poetry-core>=1.0.0",
    "setuptools",
    "cmake>=3.26,<4.0",
    "tensorflow>=2.16,<2.22",
]
build-backend = "build_backend"
backend-path = ["."]
